### ISSUE TITLE
Launch Fighters - InvalidOperationException

### ISSUE THREAD

**Issue by HunteRNeB** [stackcollision/Nebulous-BugReporting#739] opened 2024-08-20 05:09 UTC
**Describe the bug**
Selected 5 fighters, launched them.

Selected 3 more, launched them while the others were still launching.

Error popped at some point between first and second flight launching. 

**To Reproduce**

Presumably launching multiple flights one right after the other

**Expected behavior**

?

**Additional context**

In testing range

**Attachments**

(my player log freaked out after this but I got the error at the bottom. This was the one after the previous report I made)

Caught exception thrown from coroutine: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at Game.Sensors.SensorNetwork+<CalculateNextMemberReceptionPower>d__17.MoveNext () [0x0008c] in D:\Projects\Unity\Nebulous\Assets\Source\Game\Sensors\SensorNetwork.cs:82 
  at Game.Sensors.SensorContextManager+<CoroutineNetworkPowerUpdate>d__22.MoveNext () [0x00113] in D:\Projects\Unity\Nebulous\Assets\Source\Game\Sensors\SensorContextManager.cs:265 
  at Utility.CoroutineUtils+<RunThrowingIterator>d__1.MoveNext () [0x0002a] in D:\Projects\Unity\Nebulous\Assets\Source\Utility\CoroutineUtils.cs:50 
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Utility.CoroutineUtils/<RunThrowingIterator>d__1:MoveNext () (at D:/Projects/Unity/Nebulous/Assets/Source/Utility/CoroutineUtils.cs:55)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

(Filename: D:/Projects/Unity/Nebulous/Assets/Source/Utility/CoroutineUtils.cs Line: 55)

**Comment by stackcollision** [comment] 2024-08-20 18:33
Duplicate of #738, harmless.  Causes a skipped sensor cycle because the list of sensor contexts is changed.  Will be fixed eventually.

**Closed by stackcollision** 2024-08-20 18:33 UTC
Labels: bug, other errors, branch-carriers
